[package]
name = "parallel"
version = "0.2.0"
authors = ["Amish Shah <amish@shah.gg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33.3", features=["yaml"] }
